name: Bug report for .NET nanoFramework tools
description: Create a bug report related with one of our tools, like the Visual Studio extension, nanoff, etc.
labels: 
  - "Type: Bug"
  - "Status: Waiting triage"
body:
  - type: markdown
    attributes:
      value: |
        # :warning: **Please read before raising the issue** :warning:

        If you have a **question**, need clarification on something, need help on a particular situation or want to start a discussion, **DO NOT** open an issue here. _It will be automatically closed!_ 
        
        Ask the question on one of our [Discord channels](https://discordapp.com/invite/gCyBu8T), making sure to select the channel that's most appropriate to the context so subject matter experts are most likely to answer promptly. 
        If you're not keen to Discord, you can also use [GitHub Discussions](https://github.com/nanoframework/Home/discussions) in this same repo.
        Or, alternatively, on [Stack Overflow](https://stackoverflow.com/questions/tagged/nanoframework) using the `nanoframework` tag. 

        If you realy want to raise an issue, please make sure to follow the template and provide the required information. Failing to do so will most likely end up on the issue being close. Don't take offense at this. It is simply a time management decision. Whenever an issue is raised without following the template and the required information is not provided, very often too much time has to be spent going back and forth to obtain the details that are outlined below.

  - type: dropdown
    id: tool
    attributes:
      label: Tool
      description: What is the tool that you're reporting the issue.
      multiple: false
      options:
        - Visual Studio extension
        - Visual Studio Code extension
        - nanoff
        - nanodu
        - nanovc
        - Virtual nanoCLR
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: How to reproduce
      description: Detailed repro steps so we can see the same problem. If not already explained above.
      placeholder: |
        1.
        2.
        ...
    validations:
      required: false

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen. If applicable.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Very helpful if you send along a few screenshots to help visualize the issue!
      placeholder: drag and drop here, if applicable
    validations:
      required: false

  - type: textarea
    id: other_context
    attributes:
      label: Aditional context
      description: Other relevant context information like tool versions, target name(s). If applicable/relevant.
      placeholder: |
        Visual Studio version
        .NET nanoFramework extension version
        target name(s)
        firmware version
        device capabilites output
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Make an effort to fix the bug
        
        Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

        <!-- bug-report-tools-tag DO NOT REMOVE -->
